spring:
  security:
    oauth2:
      client:
        registration:
          PSSecurity:
            # https://medium.com/@bcarunmail/securing-rest-api-using-keycloak-and-spring-oauth2-6ddf3a1efcc2
            #
            client-id: spring-boot-app-template
            client-secret: 406674c6-cba9-4b2a-8fbc-4fb7c051e5f8
            scope: roles, email, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          PSSecurity:
            authorization-uri: https://office.pergersoft.hu/auth/realms/pssecurity/protocol/openid-connect/auth
            token-uri: https://office.pergersoft.hu/auth/realms/pssecurity/protocol/openid-connect/token
            user-info-uri: https://office.pergersoft.hu/auth/realms/pssecurity/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false




