keycloak:
  realm: https://office.pergersoft.hu/auth/realms/pssecurity
  account: ${keycloak.realm}/account
  application-url: https://ps-app-template.azurewebsites.net

spring:
  security:
    oauth2:
      client:
        registration:
          PSSecurity:
            # https://medium.com/@bcarunmail/securing-rest-api-using-keycloak-and-spring-oauth2-6ddf3a1efcc2
            # https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot#keycloak_configuration
            client-id: ~
            client-secret: ~
            scope: roles, email, profile
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak.application-url}/login/oauth2/code/pssecurity
        provider:
          PSSecurity:
            authorization-uri: ${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
server:
  jetty:
    max-http-form-post-size:



