keycloak:
  application-url: http://localhost:8080

spring:
  security:
    oauth2:
      client:
        registration:
          PSSecurity:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
