# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy app-frontend as JAR to private repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
        env:
          # assign the environment variable env.ARTIFACTORY_TOKEN_REF with the previously configured ARTIFACTORY_TOKEN
          ARTIFACTORY_TOKEN_REF: ${{ secrets.AZURE_DEVOPS_MAVEN_ARTIFACTORY_SECRET }}
          # assign the environment variable env.ARTIFACTORY_USERNAME_REF with the previously configured ARTIFACTORY_USERNAME
          ARTIFACTORY_USERNAME_REF: ${{ secrets.AZURE_DEVOPS_MAVEN_ARTIFACTORY_USERNAME }}

      - name: Set up settings.xml
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: '17'
          server-id: pergersoft # value of repository/id field of the pom.xml
          server-username: ARTIFACTORY_USERNAME_REF  # env variable name for username of Artifactory server; value can be anything as it is a transient user
          server-password: ARTIFACTORY_TOKEN_REF # env variable name for Artifactory access token
          # after running this action, the <username> tag contains ${env.ARTIFACTORY_USERNAME_REF} and <password> contains ${env.ARTIFACTORY_TOKEN_REF}

      - name: Build and deploy with Maven to private repository
        #run: mvn -B package
        run: cd app-frontend; mvn clean install deploy;


